# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
# Lesson.create(name: 'New Jersey v. TLO', short_desc: 'A case that examined whether school administrators have the right to search student lockers.', long_desc: '
# A New Jersey high school student was accused of violating school rules by smoking in the bathroom, leading an assistant principal to search her purse for cigarettes. The vice principal discovered marijuana and other items that implicated the student in dealing marijuana. The student tried to have the evidence from her purse suppressed, contending that mere possession of cigarettes was not a violation of school rules; therefore, a desire for evidence of smoking in the restroom did not justify the search. The Supreme Court decided that the search did not violate the Constitution and established more lenient standards for reasonableness in school searches.', grade_level: '10 to 12', subject: 'Government and Civics', lesson_text_diff_adv: "In 1980, a teacher at Piscataway High School in New Jersey found two girls smoking in a restroom. At the school, smoking in the restrooms was a violation of school rules; smoking was allowed only in the designated smoking area. The teacher escorted the two girls to the principal's office, where they met with an assistant vice principal, Theodore Choplick. One of the girls was T.L.O., a freshman who was 14 years old. The girl who was with T.L.O. admitted that she had been smoking; T.L.O., however, denied the allegation, and said that she did not, in fact, smoke at all.

# Choplick took T.L.O. into his office and instructed her to turn over her purse. He opened the purse and found a pack of cigarettes. He took the cigarettes out of the purse and showed them to T.L.O., accusing her of having lied about smoking in the restroom. As he removed the cigarettes, he noticed a package of cigarette rolling papers, which he believed were an indicator of involvement with marijuana. Therefore, he proceeded with a more thorough search of T.L.O.'s purse. This search yielded the following items: a small amount of marijuana, a pipe, empty plastic bags, a significant amount of money in one-dollar bills, a list of students who owed T.L.O. money, and letters implicating T.L.O. in dealing marijuana.

# Choplick then called T.L.O.'s mother and the police. The mother came to the school and, at the request of the police, took her daughter to the police station. Choplick turned the evidence from the purse over to the police. At the police station, T.L.O. admitted that she had been selling marijuana at school. As a result of T.L.O.'s confession and the evidence from her purse, the State of New Jersey brought delinquency charges against T.L.O. in the Juvenile and Domestic Relations Court of Middlesex County.

# T.L.O. tried to have the evidence from her purse suppressed, contending that the search violated the Fourth Amendment. She also claimed that her confession should be suppressed on the grounds that it was tainted by the unlawful search. The juvenile court rejected her Fourth Amendment arguments, although it conceded that the Fourth Amendment applies to searches by school officials. However, it held that a school official 'may search a student if that official has a reasonable suspicion that a crime has been or is in the process of being committed, or reasonable cause to believe that the search is necessary to maintain school discipline or enforce school policies.' This is a lower standard than the 'probable cause' standard, which is required when police conduct a search.

# The juvenile court concluded that Choplick's search was, therefore, reasonable. Choplick was justified in searching the purse, the Court said, because of his reasonable suspicion that T.L.O. had violated school rules by smoking in the restroom. When he opened the purse, evidence of marijuana use was in plain view; this justified the further search of the purse. T.L.O. was found to be a delinquent and, in January 1982, she was sentenced to one year of probation.

# T.L.O. appealed her conviction to the appellate division, which found no violation of the Fourth Amendment, but returned the case to juvenile court for determination of a possible Fifth Amendment problem with T.L.O.'s confession. T.L.O. then appealed the appellate division's Fourth Amendment ruling to the Supreme Court of New Jersey.

# The Supreme Court of New Jersey reversed the appellate division's ruling and ordered the evidence found in T.L.O.'s purse suppressed. The New Jersey Court relied on Supreme Court of the United States precedent to hold that whenever an official search violates constitutional rights, the evidence may not be used in a criminal case. Furthermore, the Supreme Court of New Jersey found that Choplick's search was not reasonable. Mere possession of cigarettes was not a violation of school rules; therefore, a desire for evidence of smoking in the restroom did not justify the search. In addition, the further search of the purse was not justified by the presence of cigarette rolling papers.

# In 1983, the Supreme Court of the United States granted the State of New Jersey's petition for certiorari. In 1985, the Court handed down its decision.", lesson_text_diff_int: "In 1980, a teacher at Piscataway High School in New Jersey found two girls smoking in a restroom. One of the girls was T.L.O., a freshman who was 14 years old. Smoking in the restrooms was a violation of school rules (but was permitted in other areas of the school). The teacher took the two girls to the principal's office, where they met with Assistant Vice Principal Theodore Choplick. The second girl admitted that she had been smoking. T.L.O. said she had not been smoking and said that she did not smoke at all.

# Choplick took T.L.O. into his office and instructed her to turn over her purse. He opened the purse and found a pack of cigarettes. He took the cigarettes out of the purse and showed them to T.L.O. He accused her of having lied about smoking in the restroom. As he removed the cigarettes, he noticed a package of cigarette rolling papers. He believed that cigarette rolling papers were a sign of involvement with marijuana. Therefore, he decided to search further in T.L.O.'s purse. He found the following items: a small amount of marijuana, a pipe, empty plastic bags, a significant amount of money in one-dollar bills, a list of students who owed T.L.O. money, and letters implicating T.L.O. in dealing marijuana.

# Choplick then called T.L.O.'s mother and the police. The mother came to the school. The police asked her to take her daughter to the police station. Choplick gave the items from the purse to the police. At the police station, T.L.O. admitted that she had been selling marijuana at school. As a result of her admission and the evidence from the purse, the State of New Jersey brought delinquency charges against T.L.O. in the Juvenile and Domestic Relations Court of Middlesex County.

# T.L.O. tried to have the evidence from her purse kept out of court, saying that the search violated the Fourth Amendment. She also argued that her confession should be suppressed, because it resulted from the illegal search. The juvenile court turned down her Fourth Amendment arguments, although it did agree that the Fourth Amendment applies to searches by school officials. However, it held that a school official may search a student if that official has a 'reasonable suspicion that a crime has been or is in the process of being committed, or reasonable cause to believe that the search is necessary to maintain school discipline or enforce school policies.'

# The juvenile court concluded that Choplick's search was reasonable. Choplick was justified in searching the purse, the Court said, because of his reasonable suspicion that T.L.O. had violated school rules by smoking in the restroom. When he opened the purse, evidence of marijuana use was in plain view. This justified the further search of the purse. T.L.O. was found to be a delinquent and, in January 1982, she was sentenced to one year of probation.

# T.L.O. appealed her case in the New Jersey courts. The Supreme Court of New Jersey found that Choplick's search was unreasonable. The state appealed.

# In 1983, the Supreme Court of the United States granted the State of New Jersey's petition for certiorari. In 1985, the Court handed down its decision.", lesson_text_diff_sim: "In 1980, a teacher at a high school in New Jersey found two girls smoking in a bathroom. Students were allowed to smoke in some areas of the school, but smoking in the restrooms was against school rules. The teacher took the two girls to the principal's office. There, they met with Assistant Vice Principal Theodore Choplick. One of the girls was T.L.O., a 14-year-old freshman. T.L.O. said she had not been smoking and said that she did not smoke at all. The second girl admitted that she had been smoking.

# Choplick took T.L.O. into his office. He told her to give him her purse. When he opened the purse, he found a pack of cigarettes. He took the cigarettes out of the purse and showed them to T.L.O. He said she had lied about smoking in the restroom. He also found a package of cigarette rolling papers. In his opinion, this meant that T.L.O. might be using marijuana. He decided to search T.L.O.'s purse some more. When he did so, he found some marijuana, a pipe, and empty plastic bags. He also found one-dollar bills, a list of students who owed T.L.O. money, and some letters. In the letters, there was information that showed that T.L.O. was selling marijuana.

# Choplick then called T.L.O.'s mother and the police. They both came to the school. Choplick gave the items from the purse to the police. The police asked the mother to take T.L.O. to the police station. At the police station, T.L.O. admitted that she had been selling marijuana at school. The State of New Jersey brought charges against T.L.O. The evidence they used was T.L.O.'s admission and the items from her purse.

# T.L.O. said that the search violated the Fourth Amendment protection against unreasonable search and seizure. She tried to have the evidence from her purse kept out of court. She also argued that her confession should be suppressed, because it happened as a result of the unreasonable search. The juvenile court turned down her Fourth Amendment arguments. The Court said that a school official may search a student if that official has a 'reasonable suspicion that a crime has been or is in the process of being committed'. A school official may also search a student if he has 'reasonable cause to believe that the search is necessary to maintain school discipline or enforce school policies.'

# The juvenile court concluded that Choplick's search was reasonable. It said that Choplick was justified in searching the purse because of his reasonable suspicion that T.L.O. had violated school rules by smoking in the restroom. When Choplick opened the purse, evidence of marijuana use was in plain view. This justified the further search of the purse. In January 1982, T.L.O. was found delinquent and sentenced to one year of probation.

# T.L.O. appealed her case in the New Jersey courts. The Supreme Court of New Jersey found that Choplick's search was unreasonable. The state appealed.

# In 1983, the Supreme Court of the United States agreed to hear the case. In 1985, the Court handed down its decision."

# oral_arg_one: '', oral_arg_two: '', oral_xscript_one: '', oral_xscript_two: '', question_one: "Read the Fourth Amendment to the U.S. Constitution. Using the words of the Amendment, try to make an argument that the search of T.L.O.'s purse was a violation of her Fourth Amendment rights.", question_two: 'Do you think that the Fourth Amendment should apply to students in public schools? Why or why not?', question_three: "Under the circumstances outlined above, do you think Piscataway High School's search of T.L.O.'s purse was reasonable? Why or why not?", question_four: "", question_five: '')
