# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Lesson.create(name: 'New Jersey v. TLO', short_desc: 'A case that examined whether school administrators have the right to search student lockers.', long_desc: '
A New Jersey high school student was accused of violating school rules by smoking in the bathroom, leading an assistant principal to search her purse for cigarettes. The vice principal discovered marijuana and other items that implicated the student in dealing marijuana. The student tried to have the evidence from her purse suppressed, contending that mere possession of cigarettes was not a violation of school rules; therefore, a desire for evidence of smoking in the restroom did not justify the search. The Supreme Court decided that the search did not violate the Constitution and established more lenient standards for reasonableness in school searches.', grade_level: '10 to 12', subject: 'Government and Civics', lesson_text_diff_adv: "In 1980, a teacher at Piscataway High School in New Jersey found two girls smoking in a restroom. At the school, smoking in the restrooms was a violation of school rules; smoking was allowed only in the designated smoking area. The teacher escorted the two girls to the principal's office, where they met with an assistant vice principal, Theodore Choplick. One of the girls was <div className='tooltip'>T.L.O.,<span className='tooltiptext'>T.L.O. was referred to in official documentation by her initials due to the fact that she was a minor at the time the case was being tried. Her full name was later revealed to be Tracy Lois Odem.</span></div> a freshman who was 14 years old. The girl who was with T.L.O. admitted that she had been smoking; T.L.O., however, denied the allegation, and said that she did not, in fact, smoke at all.
            <br />
            <br />

 Choplick took T.L.O. into his office and instructed her to turn over her purse. He opened the purse and found a pack of cigarettes. He took the cigarettes out of the purse and showed them to T.L.O., accusing her of having lied about smoking in the restroom. As he removed the cigarettes, he noticed a package of cigarette rolling papers, which he believed were an indicator of involvement with marijuana. Therefore, he proceeded with a more thorough search of T.L.O.'s purse. This search yielded the following items: a small amount of marijuana, a pipe, empty plastic bags, a significant amount of money in one-dollar bills, a list of students who owed T.L.O. money, and letters implicating T.L.O. in dealing marijuana.
            <br />
            <br />

            Choplick then called T.L.O.'s mother and the police. The mother came to the school and, at the request of the police, took her daughter to the police station. Choplick turned the evidence from the purse over to the police. At the police station, T.L.O. admitted that she had been selling marijuana at school. As a result of T.L.O.'s confession and the evidence from her purse, the State of New Jersey brought delinquency charges against T.L.O. in the Juvenile and Domestic Relations Court of Middlesex County.
            <br />
            <br />

            T.L.O. tried to have the evidence from her purse suppressed, contending that the search violated the <div className='tooltip'>Fourth Amendment<span className='tooltiptext'>'The right of the people to be secure in their persons, houses, papers, and effects, against unreasonable searches and seizures, shall not be violated, and no Warrants shall issue, but upon probable cause, supported by Oath or affirmation, and particularly describing the place to be searched, and the persons or things to be seized.'</span></div>. She also claimed that her confession should be suppressed on the grounds that it was tainted by the unlawful search. The juvenile court rejected her Fourth Amendment arguments, although it conceded that the Fourth Amendment applies to searches by school officials. However, it held that a school official 'may search a student if that official has a reasonable suspicion that a crime has been or is in the process of being committed, or reasonable cause to believe that the search is necessary to maintain school discipline or enforce school policies.' This is a lower standard than the <div className='tooltip'>'probable cause'<span className='tooltiptext'>Probable cause is a requirement found in the Fourth Amendment that must usually be met before police make an arrest, conduct a search, or receive a warrant.  Courts usually find probable cause when there is a reasonable basis for believing that a crime may have been committed (for an arrest) or when evidence of the crime is present in the place to be searched (for a search).
           </span></div> standard, which is required when police conduct a search.
            <br />
            <br />

             The juvenile court concluded that Choplick's search was, therefore, reasonable. Choplick was justified in searching the purse, the Court said, because of his reasonable suspicion that T.L.O. had violated school rules by smoking in the restroom. When he opened the purse, evidence of marijuana use was in plain view; this justified the further search of the purse. T.L.O. was found to be a delinquent and, in January 1982, she was sentenced to one year of probation.
            <br />
            <br />

            T.L.O. appealed her conviction to the <div className='tooltip'>appellate division<span className='tooltiptext'>Appellate courts are the part of the judicial system that is responsible for hearing and reviewing appeals from legal cases that have already been heard in a trial-level or other lower court. People who have had an unsuccessful outcome in a trial-level or other lower court may file an appeal with an appellate court to have the decision reviewed. Appellate courts are present at the state and federal levels.</span></div>, which found no violation of the Fourth Amendment, but returned the case to juvenile court for determination of a possible <div className='tooltip'>Fifth Amendment<span className='tooltiptext'>'No person shall be held to answer for a capital, or otherwise infamous crime, unless on a presentment or indictment of a Grand Jury, except in cases arising in the land or naval forces, or in the Militia, when in actual service in time of War or public danger; nor shall any person be subject for the same offence to be twice put in jeopardy of life or limb; nor shall be compelled in any criminal case to be a witness against himself, nor be deprived of life, liberty, or property, without due process of law; nor shall private property be taken for public use, without just compensation.'' </span></div> problem with T.L.O.'s confession. T.L.O. then appealed the appellate division's Fourth Amendment ruling to the Supreme Court of New Jersey.
            <br />
            <br />

            The Supreme Court of New Jersey reversed the appellate division's ruling and ordered the evidence found in T.L.O.'s purse suppressed. The New Jersey Court relied on Supreme Court of the United States <div className='tooltip'>precedent<span className='tooltiptext'>A case or issue decided by a court that can be used to help answer future legal questions.</span></div> to hold that whenever an official search violates constitutional rights, the evidence may not be used in a criminal case. Furthermore, the Supreme Court of New Jersey found that Choplick's search was not reasonable. Mere possession of cigarettes was not a violation of school rules; therefore, a desire for evidence of smoking in the restroom did not justify the search. In addition, the further search of the purse was not justified by the presence of cigarette rolling papers.
            <br />
            <br />

             In 1983, the Supreme Court of the United States granted the State of New Jersey's petition for certiorari. In 1985, the Court handed down its decision."

oral_arg_one: '', oral_arg_two: '', question_one: "Read the Fourth Amendment to the U.S. Constitution. Using the words of the Amendment, try to make an argument that the search of T.L.O.'s purse was a violation of her Fourth Amendment rights.", question_two: 'Do you think that the Fourth Amendment should apply to students in public schools? Why or why not?', question_three: "Under the circumstances outlined above, do you think Piscataway High School's search of T.L.O.'s purse was reasonable? Why or why not?", question_four: "", question_five: '')
